---
name: "Unit tests and docker image build"
on:
  push:
    branches: ['**']
  release:
    types: [prereleased, released]
env:
  BASE_IMAGE_NAME: "${{ vars.DOCKER_ORG }}/geospaas:2.5.2.dev0-slim"
  METANORM_VERSION: '4.1.0'
jobs:
  tests:
    runs-on: 'ubuntu-20.04'
    env:
      GEOSPAAS_DB_HOST: 'db'
      GEOSPAAS_DB_USER: 'test'
      GEOSPAAS_DB_PASSWORD: ${{ secrets.GEOSPAAS_DB_PASSWORD }}
      IMAGE_NAME: 'harvesting_tests'
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v2

      - name: 'Create test docker network'
        run: docker network create testing

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-testing-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-testing-

      - name: Build testing image
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: .
          target: base
          build-args: |
            BASE_IMAGE=${{ env.BASE_IMAGE_NAME }}
            METANORM_VERSION=${{ env.METANORM_VERSION }}
          push: false
          load: true
          tags: ${{ env.IMAGE_NAME }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: 'Start testing database'
        run: /bin/bash ./scripts/start_test_database.sh

      - name: 'Run tests'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: >
             docker run --rm
             --network testing
             -v "$(pwd):/src"
             -e "GITHUB_ACTIONS=$GITHUB_ACTIONS"
             -e "GITHUB_REF=$GITHUB_REF"
             -e "GITHUB_SHA=$GITHUB_SHA"
             -e "GITHUB_HEAD_REF=$GITHUB_HEAD_REF"
             -e "GITHUB_REPOSITORY=$GITHUB_REPOSITORY"
             -e "GITHUB_RUN_ID=$GITHUB_RUN_ID"
             -e "GITHUB_TOKEN=$GITHUB_TOKEN"
             -e "GEOSPAAS_DB_HOST=$GEOSPAAS_DB_HOST"
             -e "GEOSPAAS_DB_USER=$GEOSPAAS_DB_USER"
             -e "GEOSPAAS_DB_PASSWORD=$GEOSPAAS_DB_PASSWORD"
             "${IMAGE_NAME}"
             bash -c "coverage run ./runtests.py && coverage combine"

      - name: 'Stop testing database'
        run: docker stop "$GEOSPAAS_DB_HOST"

      - name: 'Install Python 3.7'
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      - name: 'Upload coverage to coveralls.io'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pip install coveralls && coveralls --service=github

  build_docker_image:
    runs-on: 'ubuntu-20.04'
    needs: 'tests'
    env:
      IMAGE_NAME: "${{ vars.DOCKER_ORG }}/geospaas_harvesting"
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v2

      - name: "Extract tag name"
        id: get_git_tag
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]];then
            TAG="${GITHUB_REF#refs/tags/}"
          else
            TAG='tmp'
          fi
          echo "version=$TAG" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-building-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-building-
            ${{ runner.os }}-buildx-testing-

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: "Make Docker tags"
        id: make_docker_tags
        run: |
          TAGS='${{ env.IMAGE_NAME }}:${{ steps.get_git_tag.outputs.version }}'
          if [[ '${{ github.event.action }}' == released ]];then
            TAGS="$TAGS,${{ env.IMAGE_NAME }}:latest"
          fi
          echo "tags=$TAGS" >> $GITHUB_OUTPUT

      - name: Build docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          build-args: |
            BASE_IMAGE=${{ env.BASE_IMAGE_NAME }}
            METANORM_VERSION=${{ env.METANORM_VERSION }}
            GEOSPAAS_HARVESTING_RELEASE=${{ steps.get_git_tag.outputs.version }}
          push: ${{ github.event_name == 'release' }}
          tags: ${{ steps.make_docker_tags.outputs.tags }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
...